<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>customer-support-crm-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CustomerSupportCrm.Application/CustomerSupportCrm.Application.csproj" />
    <ProjectReference Include="../CustomerSupportCrm.Infrastructure/CustomerSupportCrm.Infrastructure.csproj" />
    <ProjectReference Include="../CustomerSupportCrm.Contracts/CustomerSupportCrm.Contracts.csproj" />
  </ItemGroup>

</Project>
